import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SECRET_PATTERNS = [
    re.compile(r"figd_[A-Za-z0-9_-]{12,}"),
    re.compile(r"github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(r"ghp_[A-Za-z0-9]{20,}"),
    re.compile(r"sk-[A-Za-z0-9]{20,}"),
    re.compile(r"(?i)(api[_-]?key|token|secret)\s*[:=]\s*['\"][^'\"]{12,}['\"]"),
]


@dataclass
class Finding:
    severity: str
    path: str
    message: str


def run(command: list[str]) -> str:
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())
    return result.stdout


def changed_files(base: str) -> list[str]:
    output = run(["git", "diff", "--name-only", f"{base}...HEAD"])
    return [line.strip() for line in output.splitlines() if line.strip()]


def read_text(path: str) -> str:
    try:
        return (ROOT / path).read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return ""
    except FileNotFoundError:
        return ""


def review_files(files: list[str]) -> list[Finding]:
    findings: list[Finding] = []
    changed = set(files)

    for path in files:
        text = read_text(path)
        if "__pycache__" in path or path.endswith(".pyc"):
            findings.append(Finding("error", path, "Generated Python cache files should not be committed."))
        if path.startswith(".github/workflows/") and "pull_request_target" in text:
            if "checkout@v4" in text:
                findings.append(
                    Finding(
                        "warning",
                        path,
                        "`pull_request_target` with checkout needs careful review because it can expose repository tokens to untrusted PR code.",
                    )
                )
        for pattern in SECRET_PATTERNS:
            if pattern.search(text):
                findings.append(Finding("error", path, "Possible token, API key, or secret found. Remove it before merge."))

    if any(path.startswith("prompts/raw/") for path in files):
        if "docs/prompt-catalog.md" not in changed:
            findings.append(
                Finding(
                    "warning",
                    "docs/prompt-catalog.md",
                    "Prompt files changed but the generated prompt catalog was not updated.",
                )
            )

    if "prompts/figma-layer-contract.txt" in changed:
        expected = {"README.md", "evals/cases/figma-extended-prompt-frame.json"}
        missing = [path for path in expected if path not in changed]
        if missing:
            findings.append(
                Finding(
                    "warning",
                    "prompts/figma-layer-contract.txt",
                    f"Figma contract changed; consider updating related files: {', '.join(missing)}.",
                )
            )

    if "prompts/schema/prompt.schema.json" in changed:
        expected = {"README.md", "prompts/raw/nous-central-v1.json"}
        missing = [path for path in expected if path not in changed]
        if missing:
            findings.append(
                Finding(
                    "warning",
                    "prompts/schema/prompt.schema.json",
                    f"Schema changed; consider updating docs/examples: {', '.join(missing)}.",
                )
            )

    return findings


def render_markdown(files: list[str], findings: list[Finding]) -> str:
    lines = [
        "## Automated code review",
        "",
        "This review is generated by repository automation. It does not replace maintainer review.",
        "",
        f"Changed files reviewed: `{len(files)}`",
        "",
    ]
    if not findings:
        lines.extend(
            [
                "No blocking findings detected by the automated checks.",
                "",
                "Maintainer checklist:",
                "- Confirm the change matches the issue or PR scope.",
                "- Confirm validation output is included in the PR.",
                "- Review behavior manually for docs, workflows, and prompt semantics.",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(["### Findings", ""])
    severity_order = {"error": 0, "warning": 1, "info": 2}
    for finding in sorted(findings, key=lambda item: severity_order.get(item.severity, 99)):
        lines.append(f"- **{finding.severity.upper()}** `{finding.path}`: {finding.message}")
    lines.extend(
        [
            "",
            "Suggested validation:",
            "",
            "```bash",
            "python scripts/validate_repo.py",
            "python -m py_compile install/scaffold.py scripts/*.py",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an automated PR code review.")
    parser.add_argument("--base", default="origin/main", help="Base ref to diff against")
    parser.add_argument("--output", type=Path, default=ROOT / "docs/code-review-report.md")
    args = parser.parse_args()

    files = changed_files(args.base)
    findings = review_files(files)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(files, findings), encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)}")
    if any(finding.severity == "error" for finding in findings):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
