import argparse
import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs/outreach/collaborator-shortlist.md"
TOPICS = [
    "prompt-engineering",
    "mcp",
    "figma-api",
    "python",
    "jsonschema",
    "developer-tools",
    "llm-evals",
]


ROLE_RULES = {
    "MCP Developer": {
        "keywords": ["mcp", "model-context-protocol"],
        "suggested_issue": "Implement or extend `mcp/server.py` prompt tools.",
    },
    "Figma API Developer": {
        "keywords": ["figma", "figma-api", "figma-plugin"],
        "suggested_issue": "Build the Figma `PROMPT/<id>` frame importer.",
    },
    "Prompt Eval Maintainer": {
        "keywords": ["prompt", "eval", "llm-evals", "prompt-engineering"],
        "suggested_issue": "Add prompt eval checks and realistic fixtures.",
    },
    "Python Tooling Contributor": {
        "keywords": ["python", "jsonschema", "developer-tools"],
        "suggested_issue": "Improve validation, catalog generation, and CLI tooling.",
    },
}


@dataclass
class Candidate:
    login: str
    role: str
    score: int = 0
    reasons: list[str] = field(default_factory=list)
    repos: list[str] = field(default_factory=list)


def run_gh(args: list[str]) -> object:
    result = subprocess.run(["gh", *args], cwd=ROOT, text=True, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())
    return json.loads(result.stdout)


def search_repositories(topic: str, limit: int) -> list[dict]:
    query = f"topic:{topic} archived:false"
    return run_gh(
        [
            "search",
            "repos",
            query,
            "--limit",
            str(limit),
            "--json",
            "fullName,description,stargazersCount,updatedAt,language,owner,url",
        ]
    )


def role_for_repo(repo: dict) -> tuple[str, list[str]]:
    text_parts = [
        repo.get("fullName", ""),
        repo.get("description") or "",
        repo.get("language") or "",
    ]
    text = " ".join(part for part in text_parts if part).lower()

    best_role = "Python Tooling Contributor"
    best_matches: list[str] = []
    for role, rule in ROLE_RULES.items():
        matches = [keyword for keyword in rule["keywords"] if keyword in text]
        if len(matches) > len(best_matches):
            best_role = role
            best_matches = matches
    return best_role, best_matches


def add_candidate(candidates: dict[str, Candidate], repo: dict) -> None:
    owner = repo.get("owner") or {}
    login = owner.get("login")
    if not login:
        return

    role, matches = role_for_repo(repo)
    candidate = candidates.setdefault(login, Candidate(login=login, role=role))
    if candidate.role == "Python Tooling Contributor" and role != candidate.role:
        candidate.role = role

    stars = repo.get("stargazersCount") or 0
    score = 1
    score += min(stars // 25, 5)
    score += min(len(matches), 3)
    score += 2 if repo.get("language") == "Python" else 0
    candidate.score += score

    repo_name = repo.get("fullName", "unknown")
    if repo_name not in candidate.repos:
        candidate.repos.append(repo_name)
    reason = f"Maintains or owns `{repo_name}` matching {', '.join(matches or ['related search topics'])}."
    if reason not in candidate.reasons:
        candidate.reasons.append(reason)


def render(candidates: list[Candidate]) -> str:
    lines = [
        "# Potential collaborators",
        "",
        "Generated by `scripts/scout_collaborators.py`.",
        "",
        "This shortlist is for manual review only. Do not mass-mention or automatically contact people.",
        "",
        "## Outreach rules",
        "",
        "- Contact only a small number of highly relevant people.",
        "- Personalize every message.",
        "- Offer a clear, small issue they can review or claim.",
        "- Do not add people to issues without consent.",
        "",
    ]

    grouped: dict[str, list[Candidate]] = {}
    for candidate in candidates:
        grouped.setdefault(candidate.role, []).append(candidate)

    for role, role_candidates in grouped.items():
        lines.append(f"## {role}")
        lines.append("")
        suggested_issue = ROLE_RULES.get(role, ROLE_RULES["Python Tooling Contributor"])["suggested_issue"]
        for candidate in role_candidates[:5]:
            lines.append(f"- @{candidate.login}")
            lines.append(f"  - Score: {candidate.score}")
            lines.append(f"  - Reason: {candidate.reasons[0]}")
            lines.append(f"  - Repos: {', '.join(candidate.repos[:3])}")
            lines.append(f"  - Suggested issue: {suggested_issue}")
            lines.append("  - Outreach draft:")
            lines.append("")
            lines.append("    ```text")
            lines.append(f"    Hi @{candidate.login},")
            lines.append("    ")
            lines.append("    I am building Hermes Figma Prompt Hub, an open-source project for Figma-to-MCP prompt management.")
            lines.append(f"    Your work looks relevant for {role.lower()} tasks, especially: {suggested_issue}")
            lines.append("    ")
            lines.append("    Repo: https://github.com/jozrftamson/hermes-figma-prompt-hub")
            lines.append("    If this is interesting, I would welcome a small PR or feedback on the related issue.")
            lines.append("    ```")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Scout potential collaborators from public GitHub repositories.")
    parser.add_argument("--limit-per-topic", type=int, default=8)
    parser.add_argument("--max-candidates", type=int, default=20)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    args = parser.parse_args()

    candidates: dict[str, Candidate] = {}
    for topic in TOPICS:
        for repo in search_repositories(topic, args.limit_per_topic):
            add_candidate(candidates, repo)

    ranked = sorted(candidates.values(), key=lambda item: item.score, reverse=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(ranked[: args.max_candidates]), encoding="utf-8")
    print(f"Wrote {args.output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
